Burned Areas Tile Cache
wri/gfw-tile-cache pull request #84
Opened 2021-06-02 20:00 UTC by jterry64

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [X] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [X] Check the commit's or even all commits' message styles matches our requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the new behavior?

- Create special routes for burned areas to allow date filtering and ordering behavior
- Allow you to specify order_by columns when creating the tile cache query
- Some refactoring so the routes could share code better with the VIIRS routes code

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2021-06-10 14:08 UTC, thomas-maschler requested changes
Overall looks good. 
Can you please add some additional tests for the work you have done?
Test coverage is already poor and we should make efforts to have it not degrade any further.

2021-06-10 14:08 UTC, thomas-maschler commented on app/crud/async_db/vector_tiles/__init__.py
> +    cols: List[ColumnClause] = deepcopy(columns)
to be curious, why deep copy? you do not alter the columns, do you?

2021-06-10 14:08 UTC, thomas-maschler commented on app/crud/async_db/vector_tiles/umd_modis_burned_areas.py
> +    query = get_mvt_table(SCHEMA, version, bbox, extent, COLUMNS, filters, order_by)
I would make this part of the route. This way you don't need to override the `get_tile` method here and you could skip the entire module.

2021-06-10 14:08 UTC, thomas-maschler commented on app/routes/nasa_viirs_fire_alerts/__init__.py
> +    return now.to_date_string()
should we make an API call here and set default end to the latest date in the dataset?
We could include this in the crud/sync module and also fetch the content date range when it exists

2021-06-10 14:08 UTC, thomas-maschler commented on app/routes/umd_modis_burned_areas/__init__.py
> +    return now.to_date_string()
Same as above

2021-06-10 14:21 UTC, jterry64 commented on app/crud/async_db/vector_tiles/__init__.py
> +    cols: List[ColumnClause] = deepcopy(columns)
I think I was but then changed how I was doing things, I'll get rid of it

2021-06-10 14:31 UTC, jterry64 commented on app/routes/nasa_viirs_fire_alerts/__init__.py
> +    return now.to_date_string()
that's a good idea, and we can just do now() as a backup if it doesn't exist

2021-06-10 21:03 UTC, thomas-maschler requested changes

2021-06-10 21:03 UTC, thomas-maschler commented on app/crud/async_db/vector_tiles/__init__.py
> +    cols: List[ColumnClause] = list(columns)
This already comes as list

2021-06-10 21:03 UTC, thomas-maschler commented on app/crud/sync_db/tile_cache_assets.py
> +                    return tile_cache["max_date"]
```suggestion
            if version and tile_cache["version"] == version:
                    return tile_cache["max_date"]
```

2021-06-14 20:50 UTC, jterry64 commented
@thomas-maschler fixed your comments and added some tests!

2021-06-15 03:14 UTC, thomas-maschler approved these changes

2021-06-15 14:37 UTC, merged